version: '{build}'
environment:
  CYGWIN_ROOT: C:\cygwin64
  CYGWIN_MIRROR: http://cygwin.mirror.constant.com
  CYGWIN_CACHE: C:\cache
  matrix:
  - HOST: i686-w64-mingw32
  - HOST: x86_64-w64-mingw32
install:
 - if "%HOST%"=="i686-w64-mingw32" set PKGARCH="mingw64-i686"
 - if "%HOST%"=="x86_64-w64-mingw32" set PKGARCH="mingw64-x86_64"
 - if NOT DEFINED PKGARCH exit 1
 - set SETUP=setup-x86_64.exe
 - appveyor DownloadFile http://cygwin.com/%SETUP% -FileName %CYGWIN_ROOT%\%SETUP%
 - echo Updating Cygwin and installing build prerequisites
 - "%CYGWIN_ROOT%\\%SETUP% -qnNdO -R %CYGWIN_ROOT% -s %CYGWIN_MIRROR% -l %CYGWIN_CACHE% -g -P \
autoconf,\
automake,\
bison,\
flex,\
libtool,\
make,\
%PKGARCH%-bzip2,\
%PKGARCH%-gcc-g++,\
%PKGARCH%-headers,\
%PKGARCH%-libgcrypt,\
%PKGARCH%-libsolv,\
%PKGARCH%-xz,\
%PKGARCH%-zlib,\
%PKGARCH%-zstd,\
pkg-config,\
upx"
build_script:
 - echo Bootstrap ...
 - '%CYGWIN_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./bootstrap.sh --host=%HOST%"'
 - echo Make ...
 - '%CYGWIN_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; make"'
 - echo Tests ...
 - '%CYGWIN_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; export PATH=/usr/${HOST}/sys-root/mingw/bin/:${PATH} ; make check"'
 - echo Strip/UPX ...
 - '%CYGWIN_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; make strip upx"'
cache: C:\cache
test: off
deploy: off
artifacts:
- path: setup.exe
