#!/bin/bash
set -e

DIR=`dirname "$0"`

# Autotool Bootstrap
if [ ! -f "$DIR/configure" ]; then
  echo -e "\033[32;1mRunning $DIR/bootstrap.sh\033[0m"
  ( cd "$DIR" && ./bootstrap.sh )
fi

# If $build == cygwin, set PATH so that correct (mingw)
# version of gpg-error-config and libgcrypt-config are
# used.  Otherwise: assume cross-compiler users are
# sophisticated enough to do this manually.
case `uname -s` in
*CYGWIN* ) export PATH="/usr/lib/mingw:${PATH}" ;;
esac

# Configure
cmd="\"$DIR/configure\""
cmd=$cmd' -C --disable-shared --enable-maintainer-mode'
cmd=$cmd' --host=i686-pc-mingw32 --build=i686-pc-cygwin'
cmd=$cmd' CC="gcc-3 -mno-cygwin" CXX="g++-3 -mno-cygwin"'

for i in "$@"; do
  case $i in
    maint) cmd=$cmd' CPPFLAGS=-DMAINTAINER_FEATURES' ;;
    debug) cmd=$cmd' CFLAGS="-g -O0" CXXFLAGS="-g -O0"' ;;
    *) echo "Unexpected argument: '$i'" >&2; exit 1 ;;
  esac
done

echo -e "\033[32;1mRunning $DIR/configure\033[0m"
eval "$cmd"
