// Strings

#define IDS_ROOT_SLASH                    100
#define IDS_ROOT_SPACE                    101
#define IDS_ERR_OPEN_WRITE                103
#define IDS_SETUPINI_MISSING              104
#define IDS_OLD_SETUPINI                  105
#define IDS_NOTHING_INSTALLED             106
#define IDS_INSTALL_COMPLETE              107
#define IDS_ERR_OPEN_READ                 108
#define IDS_ROOT_ABSOLUTE                 109
#define IDS_DOWNLOAD_COMPLETE             110
#define IDS_NOLOGFILE                     111
#define IDS_UNINSTALL_COMPLETE            112
#define IDS_ERR_CHDIR                     114
#define IDS_OLD_SETUP_VERSION             115
#define IDS_DOWNLOAD_INCOMPLETE           116
#define IDS_INSTALL_INCOMPLETE            117
#define IDS_REBOOT_REQUIRED               118
#define IDS_CORRUPT_PACKAGE               119
#define IDS_INSTALL_ERROR                 120
#define IDS_UNCAUGHT_EXCEPTION            122
#define IDS_UNCAUGHT_EXCEPTION_WITH_ERRNO 123
#define IDS_SKIP_PACKAGE                  124
#define IDS_TRUSTKEEP_TOOLTIP             125
#define IDS_TRUSTCURR_TOOLTIP             127
#define IDS_TRUSTEXP_TOOLTIP              128
#define IDS_VIEWBUTTON_TOOLTIP            129
#define IDS_HIDEOBS_TOOLTIP               130
#define IDS_SIG_INVALID                   131
#define IDS_CRYPTO_ERROR                  132
#define IDS_SEARCH_TOOLTIP                133
#define IDS_MAYBE_MKDIR                   136
#define IDS_CANT_MKDIR                    137
#define IDS_NO_LOCALDIR                   138
#define IDS_ELEVATED                      139
#define IDS_INSTALLEDB_VERSION            140
#define IDS_DOWNLOAD_INCOMPLETE_EXIT      141
#define IDS_QUERY_CORRUPT                 142
#define IDS_TRUSTSYNC_TOOLTIP             143
#define IDS_NO_MIRROR_LST                 144
#define IDS_PROGRESS_PROGRESS             145
#define IDS_PROGRESS_PACKAGE              146
#define IDS_PROGRESS_CONNECTING           147
#define IDS_PROGRESS_CHECKING             148
#define IDS_PROGRESS_DOWNLOADING          149
#define IDS_PROGRESS_PARSING              150
#define IDS_PROGRESS_PREREMOVE            151
#define IDS_PROGRESS_UNINSTALL            152
#define IDS_PROGRESS_INSTALL              153
#define IDS_PROGRESS_CALCULATING          154
#define IDS_PROGRESS_POSTINSTALL          155
#define IDS_PROGRESS_SOLVING              156
#define IDS_ACTION_DEFAULT                157
#define IDS_ACTION_SKIP                   158
#define IDS_ACTION_KEEP                   159
#define IDS_ACTION_INSTALL                160
#define IDS_ACTION_UNINSTALL              161
#define IDS_ACTION_REINSTALL              162
#define IDS_ACTION_RETRIEVE               163
#define IDS_ACTION_UNKNOWN                164
#define IDS_ACTION_SOURCE                 165
#define IDS_VIEW_FULL                     166
#define IDS_VIEW_PENDING                  167
#define IDS_VIEW_UPTODATE                 168
#define IDS_VIEW_NOTINSTALLED             169
#define IDS_VIEW_PICKED                   170
#define IDS_VIEW_CATEGORY                 171
#define IDS_COLUMN_PACKAGE                172
#define IDS_COLUMN_CURRENT                173
#define IDS_COLUMN_NEW                    174
#define IDS_COLUMN_SOURCE                 175
#define IDS_COLUMN_CATEGORIES             176
#define IDS_COLUMN_SIZE                   177
#define IDS_COLUMN_DESCR                  178
#define IDS_MBOX_CAPTION                  179
#define IDS_EXTRACTION_FAILED             180
#define IDS_INSTALL_DELETE_OLD_CYGWIN_FAILED 181
#define IDS_INSTALL_OLD_CYGWIN            182
#define IDS_SHELLLINK_FAILED              183
#define IDS_UNSUPPORTED_WINDOWS_VERSION   184
#define IDS_MOUNT_REGISTRY_KEY_FAILED     185
#define IDS_NIO_ERROR                     186
#define IDS_PREREQ_UNSOLVED_PROBLEMS      187
#define IDS_MIXED_BITNESS_ERROR           188
#define IDS_GET_SITELIST_ERROR            189
#define IDS_CONFIRM_EXIT                  190
#define IDS_EXTRACTION_INUSE              191
#define IDS_CONTINUE                      192
#define IDS_CHOOSER_EMPTY_NO_PACKAGES     193
#define IDS_CHOOSER_EMPTY_DOWNLOAD        194
#define IDS_CHOOSER_EMPTY_INSTALL         195

// Dialogs

#define IDD_SPLASH                        200
#define IDD_ROOT                          201
#define IDD_SOURCE                        202
#define IDD_OTHER_URL                     203
#define IDD_SITE                          204
#define IDD_NET                           205
#define IDD_PROXY_AUTH                    206
#define IDD_NET_AUTH                      207
#define IDD_FTP_AUTH                      208
#define IDD_LOCAL_DIR                     209
#define IDD_DLSTATUS                      210
#define IDD_S_LOAD_INI                    211
#define IDD_S_FROM_CWD                    212
#define IDD_CHOOSE                        213
#define IDD_S_DOWNLOAD                    214
#define IDD_S_INSTALL                     215
#define IDD_INSTATUS                      216
#define IDD_S_POSTINSTALL                 217
#define IDD_VIRUS                         218
#define IDD_DESKTOP                       219
#define IDD_PREREQ                        220
#define IDD_DROPPED                       221
#define IDD_POSTINSTALL                   222
#define IDD_FILE_INUSE                    223
#define IDD_DOWNLOAD_ERROR                224
#define IDD_CONFIRM                       225

// icons

#define IDI_CYGWIN_SETUP                  401
#define IDI_CYGWIN                        402
#define IDI_CYGWIN_TERMINAL               403
#define IDI_TREE_PLUS                     404
#define IDI_TREE_MINUS                    405

// controls

#define IDC_STATIC                         -1
#define IDC_SOURCE_DOWNLOAD               500
#define IDC_SOURCE_NETINST                501
#define IDC_SOURCE_LOCALDIR               502
#define IDC_ROOT_DIR                      503
#define IDC_ROOT_BROWSE                   504
#define IDC_SOURCE_SUBTEXT		  505
#define IDC_URL_LIST                      507
#define IDC_SITE_NEXT                     508
#define IDC_BACK                          509
#define IDC_OTHER_URL                     510
#define IDC_NET_PRECONFIG                 511
#define IDC_NET_DIRECT                    512
#define IDC_NET_PROXY                     513
#define IDC_PROXY_HOST                    514
#define IDC_PROXY_PORT                    515
#define IDC_PROXY_USER                    516
#define IDC_DLS_PROGRESS                  517
#define IDC_DLS_URL                       518
#define IDC_DLS_RATE                      519
#define IDC_INS_PKG                       520
#define IDC_INS_FILE                      521
#define IDC_INS_DISKFULL                  522
#define IDC_INS_IPROGRESS                 523
#define IDC_INS_PPROGRESS                 524
#define IDC_ROOT_SYSTEM                   525
#define IDC_ROOT_USER                     526
#define IDC_NET_USER                      527
#define IDC_NET_PASSWD                    528
#define IDC_VERSION                       529
#define IDC_CHOOSE_VIEW                   531
#define IDC_CHOOSE_EXP                    532
#define IDC_CHOOSE_BEST                   533
#define IDC_CHOOSE_LIST                   535
#define IDC_INS_ACTION                    536
#define IDC_ROOT_DESKTOP                  537
#define IDC_ROOT_MENU                     538
#define IDC_LOCAL_DIR_BROWSE              539
#define IDC_LOCAL_DIR                     540
#define IDC_DLS_PPROGRESS                 541
#define IDC_DLS_IPROGRESS                 542
#define IDC_DLS_PROGRESS_TEXT             543
#define IDC_DLS_PPROGRESS_TEXT            544
#define IDC_DLS_IPROGRESS_TEXT            545
#define IDC_CHOOSE_INST_TEXT_DOWNLOAD     546
#define IDC_CHOOSE_VIEWCAPTION            547
#define IDC_INS_BL_PACKAGE                549
#define IDC_INS_BL_TOTAL                  550
#define IDC_INS_BL_DISK                   551
#define IDC_STATIC_HEADER_TITLE           552
#define IDC_STATIC_WELCOME_TITLE          553
#define IDC_EDIT_USER_URL                 554
#define IDC_BUTTON_ADD_URL                555
#define IDC_DISABLE_AV                    556
#define IDC_LEAVE_AV                      557
#define IDC_CHOOSE_KEEP                   558
#define IDC_HEADICON                      559
#define IDC_HEADSEPARATOR                 560
#define IDC_SPLASH_URL                    561
#define IDC_ROOTDIR_SUBTEXT               562
#define IDC_ROOTDIR_GRP                   563
#define IDC_INSTALLFOR_GRP                564
#define IDC_ALLUSERS_TEXT                 565
#define IDC_JUSTME_TEXT                   566
#define IDC_LOCALDIR_GRP                  570
#define IDC_SPLASH_TEXT                   571
#define IDC_SPLASH_ICON                   572
#define IDC_SPLASH_COPYR                  573
#define IDC_SITE_USERURL                  574
#define IDC_CHOOSE_HIDE                   575
#define IDC_PREREQ_TEXT                   576
#define IDC_PREREQ_EDIT                   577
#define IDC_PREREQ_CHECK                  578
#define IDC_DROP_MIRRORS                  579
#define IDC_DROP_NOWARN                   580
#define IDC_DESKTOP_SEPARATOR             581
#define IDC_STATUS_HEADER                 582
#define IDC_STATUS                        583
#define IDC_STATIC_HEADER                 584
#define IDC_CHOOSE_SEARCH_EDIT            585
#define IDC_CHOOSE_SEARCH_LABEL           586
#define IDC_CHOOSE_CLEAR_SEARCH           587
#define IDC_POSTINSTALL_EDIT              589
#define IDC_FILE_INUSE_EDIT               590
#define IDC_FILE_INUSE_MSG                591
#define IDC_FILE_INUSE_HELP               592
#define IDC_DOWNLOAD_EDIT                 594
#define IDC_CHOOSE_DO_SEARCH              595
#define IDC_CHOOSE_SYNC                   596
#define IDC_CONFIRM_EDIT                  597
#define IDC_CHOOSE_INST_TEXT_INSTALL      598
#define IDC_DESKTOP_HEADER_DOWNLOAD       599
#define IDC_DESKTOP_HEADER_TITLE_DOWNLOAD 600
#define IDC_DESKTOP_HEADER_INSTALL        601
#define IDC_DESKTOP_HEADER_TITLE_INSTALL  602
#define IDC_LOCAL_DIR_DOWNLOAD_DESC       603
#define IDC_LOCAL_DIR_INSTALL_DESC        604
